# Development stage (optional, can be used for debugging and as a devcontainer)
FROM node:22-alpine AS development
WORKDIR /app
ENV NODE_ENV=development
COPY package*.json ./
RUN apk add --no-cache git
# Rebuild a clean node_modules based on the package-lock.json to ensure consistency
RUN npm install --package-lock-only
RUN npm ci
USER node
COPY . .
EXPOSE 3000
# Sleep for infinite time to keep the container running for debugging purposes
CMD ["sleep", "infinity"]

