# Development stage (optional, can be used for debugging and as a devcontainer)
FROM node:22-alpine AS development
#Setup Alpine packages for development
RUN apk add --no-cache git openssh-client
#Setup NodeJS for development
WORKDIR /app
ENV NODE_ENV=development
COPY package*.json ./
RUN npm install --package-lock-only
RUN npm ci
COPY . .
#Make sure the node user has permissions to access the app directory
RUN chown -R node:node /app
USER node
EXPOSE 3000
# Sleep for infinite time to keep the container running for debugging purposes
CMD ["sleep", "infinity"]
