name: Update OpenAPI documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
jobs:
  build-and-deploy:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development

    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: npm ci

      - name: Build OpenAPI documentation
        run: |
          npm run swagger
          npm run swagger:doc:md
          npm run swagger:doc:html

      - name: Move and rename swagger file
        run: mv docs/openapi/swagger.yaml docs/swagger.yml

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
